### ISSUE TITLE
Access to request in schema

### ISSUE THREAD

**Issue by snapiz** [sunli829/async-graphql#13]
How to pass some context to schema with `web::Json(req.into_inner().execute(&s).await)` ? like a token from request

**Comment by sunli829** [comment]
Sorry, I missed such an important feature.🤢
Please upgrade to 1.6.8, I have added it.
Here's an example https://github.com/sunli829/async-graphql/blob/master/async-graphql-actix-web/examples/token.rs, get the token from the `Header` and access it through the `Context`

**Comment by snapiz** [comment]
Very nice, Thanks
