### ISSUE TITLE
Provide example with global stream for subscription

### ISSUE THREAD

**Issue by nicolaiunrein** [sunli829/async-graphql#16]
Now that subscription handlers return a stream. What is the most idiomatic way for subscribers sharing a stream as opposed to each subscriber starting a new stream? Also is there an idiomatic way of implementing something like the publish method to emit to subscribers from a mutation handler directly?
I can think of two solutions:

1. Use lazy_static or
2. Store a channel on the SubscriptionRoot

Is there a better solution I am not aware of? I find it quite hard to migrate my code to 1.6.7 in a clean fashion.
If you could point me in the right direction I could extend the examples

**Comment by sunli829** [comment]
Global subscriptions are easy to implement, and I'll add a component tomorrow to do just that.


Creating the stream should be an asynchronous function, so I'm going to do that first.

**Comment by sunli829** [comment]
Are you Chinese?

**Comment by nicolaiunrein** [comment]
> Are you Chinese?

No German :blush:
Why?

**Comment by sunli829** [comment]
I thought we were in the same time zone.😄

I added `SimpeBroker` and updated the example.
`SimpleBroker` should be used for standalone testing, and later I will provide support for `Kafka`, `Redis`, etc.

**Comment by nicolaiunrein** [comment]
Yeah thought so too. :laughing:  Are you from china?

**Comment by sunli829** [comment]
Yes, I'm Chinese.😁

**Comment by nicolaiunrein** [comment]
SimpleBroker panics at ```called `Option::unwrap()` on a `None` value``` if used with more than one type. Is this intended? If so this should be reflected in the docs/example.

**Comment by sunli829** [comment]
The problem has been solved.😁

**Comment by sunli829** [comment]
I didn't have a test because I was going to sleep. That should be fine.

**Comment by maz000** [comment]
Can you provide a “Redis-based” (https://github.com/mitsuhiko/redis-rs) example of global stream for subscription?

**Comment by sarendsen** [comment]
I would be interested in an redis-rs example as well.

**Comment by lurahzam** [comment]
May be helpful...

publishing
``` rust
let message = serde_json::to_string(&order)?;
let channel = format!("user_{}_order", driver.user_id);
let _ = caching::cache_publish(ctx, channel, message).await?;
```
and consuming
``` rust
async fn logistics_order(
    &self,
    ctx: &Context<'_>,
    channel: String,
) -> impl Stream<Item = Order> {
    let context = ctx.data::<MainContext>().unwrap();
    let con = context.redis.get_async_connection().await.unwrap();
    let mut pubsub = con.into_pubsub();
    pubsub.subscribe(channel).await.unwrap();
    stream! {
    let mut msg_stream = pubsub.on_message();
        while let Some(msg) = msg_stream.next().await {
            let message: String = msg.get_payload().unwrap();
            let order: Order = serde_json::from_str(&message).unwrap();
            yield order;
        }
    }
}
```

**Comment by sarendsen** [comment]
Appreciated, actually just finished an implementation but using rust channels. Because this approach creates an redis connection for each subscription.

i know have one subscription channel that fansout internally to subscriptions

**Comment by lurahzam** [comment]
Can u provide some code example, it would be greatly helpful for us.

**Comment by sarendsen** [comment]
```rust
...

lazy_static! {
  pub static ref EVENT_BUS: tokio::sync::broadcast::Sender<Output> = {
    let (tx, _) = tokio::sync::broadcast::channel(10000);
    tx
  };
}

...

#[Object]
impl Mutation {
  async fn emit_eventl(&self, ctx: &Context<'_>, input: Input) -> Result<Output> {
    let mut redis_conn = ctx
      .data_unchecked::<redis::aio::MultiplexedConnection>()
      .clone();
    let _: () = redis_conn
      .publish('mychannel', serde_json::to_string(&signal)?)
      .await?;

    Ok(signal)
  }
}

...

#[Subscription]
impl Subscription {
  async fn receive_event(&self, ctx: &Context<'_>) -> impl Stream<Item = Output> {
    BroadcastStream::new(EVENT_BUS.subscribe())
      .filter(|msg| msg.is_ok())
      .map(|msg| msg.unwrap())
  }
}

....


#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
  let redis_url = env::var("REDIS_URL").expect("REDIS_URL is not set");
  let redis_client = redis::Client::open(redis_url).expect("client");
  let mut redis_pubsub = redis_client
    .clone()
    .get_tokio_connection()
    .await?
    .into_pubsub();
  let fanout_task = async move {
    redis_pubsub
      .subscribe("my channel")
      .await
      .unwrap();
    let mut msg_stream = redis_pubsub.into_on_message();
    while let Some(msg) = msg_stream.next().await {
      let msg: String = msg.get_payload().unwrap();
      let user_signal: schema::Signal = serde_json::from_str(&msg).unwrap();
      let _ = schema::EVENT_BUS.send(user_signal);
    }
  };
  // spawn the fanout task as a background task that will run forever.
  tokio::spawn(fanout_task);

  ...

}
```

**Comment by atik7** [comment]
@sunli829 Please add a redis example, thank you!

**Comment by sunli829** [comment]
Okay, I will provide it later today. @atik7

**Comment by sunli829** [comment]
@atik7 https://github.com/async-graphql/examples/tree/c8219078a4b7aa6d84d22e9b79f033088897be4b/poem/subscription-redis

**Comment by atik7** [comment]
@sunli829 thank you :-)
