### ISSUE TITLE
Serde alias gets ignored on Enums

### ISSUE THREAD

**Issue by nicolaiunrein** [sunli829/async-graphql#17]
I ran into the following bug: 
```
use serde::Deserialize;
  
#[async_graphql::Enum]
#[derive(Deserialize)]
enum Test {
  #[serde(alias = "Other")]
    Real,
  }
  
#[derive(Deserialize)]
struct TestStruct {
  value: Test,
}
  
fn main() {
  serde_json::from_str::<TestStruct>(r#"{ "value" : "Other" }"#).unwrap();
}
```

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `Other`, expected `Real`", line: 1, column: 19)', src/libcore/result.rs:1188:5```

Without the `async_graphql::Enum` annotation everything is fine.

**Comment by nicolaiunrein** [comment]
Structs do not seem to be affected. The following code runs just fine
```
use serde::Deserialize; 
  
#[async_graphql::SimpleObject]
#[derive(Deserialize)]
struct TestStruct {
    #[serde(alias = "other")]
    test: String,
}
  
fn main() {
   serde_json::from_str::<TestStruct>(r#"{ "other" : "value" }"#).unwrap();
}
```

**Comment by sunli829** [comment]
Yes, there was a problem with this place, and I ignored #derive because there was another problem, but now I can solve it.

**Comment by sunli829** [comment]
I fixed this on the master branch.
