### ISSUE TITLE
What happened to `async_graphql_actix_web::HandlerBuilder`?

### ISSUE THREAD

**Issue by nicolaiunrein** [sunli829/async-graphql#19]
I was about to upgrade from 1.7.8 to 1.9.3 when I realised that quite a lot has changed. So I looked at the examples and codebase but I could not find any info on how I would transition the below code to 1.9.3. Where do I specify `max_file_size` and `temp_dir`?

```
    HttpServer::new(move || {
        let schema = Schema::build(QueryRoot, MutationRoot, SubscriptionRoot)
            .extension(|| ApolloTracing::default())
            .finish();

        let handler = async_graphql_actix_web::HandlerBuilder::new(schema)
            .enable_ui("http://localhost:3001", Some("ws://localhost:3001"))
            .max_file_size(100_000_000_000) //100 GB
            .enable_subscription()
            .build();

        App::new()
            .wrap(Logger::default())
            .wrap(Cors::new().finish())
            .service(web::resource("/").to(handler))
    })
    .bind(format!("0.0.0.0:{}", 3001))
    .unwrap()
    .run()
```

**Comment by sunli829** [comment]
I didn't think that was flexible enough, so I just removed this.😁
`async_graphql_actix_web::GQLRequest` is an Extractor that is easier to use.
Look at this
https://github.com/sunli829/async-graphql-examples/blob/fc28d830ba0aaeac3b8ece3ec5e2f725a146aafd/actix-web/starwars/src/main.rs#L7

**Comment by sunli829** [comment]
I moved all the examples to https://github.com/sunli829/async-graphql-examples/

**Comment by sunli829** [comment]
The `max_file_size` and `tempdir` properties are not supported yet, and this is easy to add because now we have our own multipart parser(https://github.com/sunli829/async-graphql/blob/master/src/http/multipart.rs). I'll add them tomorrow.

**Comment by nicolaiunrein** [comment]
👍 I was just about to ask. I liked the builder though and I think it made it very intuitive for people getting started with the library.

**Comment by sunli829** [comment]
Builder is convenient, but not easy to combine with other Extractor, I haven't found a good way yet.

**Comment by nicolaiunrein** [comment]
I agree. And I think we should get the features straight first and can add convenience functionality once everything has settled.

**Comment by sunli829** [comment]
Take a look at this example, add some parameters.

https://github.com/sunli829/async-graphql-examples/blob/6bfcf4498a6134bee144dc770b7c18fde37e45d3/actix-web/upload/src/main.rs#L29
