### ISSUE TITLE
Interface doesn't work with SimpleObject?

### ISSUE THREAD

**Issue by phated** [sunli829/async-graphql#20]
I was trying to implement an Interface for my structs annotated with SimpleObject and it fails with `field, not a method`. Is it possible to support Interfaces using SimpleObjects?

Here's an example:
```rust
#[async_graphql::SimpleObject]
pub struct MyObj {
  #[field]
  pub id: i32,
  #[field]
  pub title: String,
};

#[async_graphql::Interface(
  field(name = "id", type = "i32"),
)]
pub struct Node(MyObj);
```

**Comment by sunli829** [comment]
Just a moment, let me have a look

**Comment by sunli829** [comment]
This is my problem, I forgot to add interface support to `SimpleObject`, so I'm going to do that。😁

**Comment by sunli829** [comment]
I solved the problem, upgrade to `1.9.7`.

Below is test:

https://github.com/sunli829/async-graphql/blob/6a3c54613bb7e18ec8f1a6a50f06c48059ae77d3/tests/interface.rs#L4

https://github.com/sunli829/async-graphql/blob/6a3c54613bb7e18ec8f1a6a50f06c48059ae77d3/tests/interface.rs#L51

**Comment by phated** [comment]
There seems to be a different issue, but I'm investigating my code now.

**Comment by phated** [comment]
This is working now. Thank you! 🙇
