### ISSUE TITLE
Is it possible to pass session data (or other actix middleware data) into the GraphQL execution context?

### ISSUE THREAD

**Issue by Ejhfast** [sunli829/async-graphql#21]
First, awesome work on this library! I started using it with actix as Juniper doesn't support subscriptions well and so far everything has worked great. But I've recently run into an issue:

Is it possible to pass actix-web session data into the execution context of a GraphQL resolver? I would like to use this to authenticate certain queries against a session token. Poor pseudocode for what I'm looking to accomplish would be:

```rust
impl QueryRoot {
    #[field]
    async fn conversations(&self, ctx: &Context<'_>) -> Option<Vec<Conversation>> {
        // the line below is what I would like to accomplish. how to get session data in here?
        let token = ctx.data::<Session>().get("token");
        // then validation is easy. I have the db from Schema::build(..).data(...)
        let db = ctx.data::<Database>();
        match validate(token, db) {
            Some(result) => Some(db.get_all().await),
            None => None
        }
    }
}
```

In Juniper, it seems like you can extend the Context to do something similar. For example, [this issue](https://github.com/graphql-rust/juniper/issues/373) led to the suggestion: https://github.com/davidpdrsn/graphql-app-example/blob/master/src/graphql.rs#L20

Any ideas how to best accomplish this here? I'd be happy to document it with an example if someone could help me figure it out. Ideally, it would be nice to use [actix-session](https://docs.rs/actix-session/0.4.0-alpha.1/actix_session/index.html) or something similar.

**Comment by sunli829** [comment]
Here's an example:
https://github.com/sunli829/async-graphql-examples/tree/master/actix-web/token-from-header

**Comment by Ejhfast** [comment]
Thank you! Can't believe I missed that, should have double checked in the examples

**Comment by sunli829** [comment]
The document is not very detailed.😁
