### ISSUE TITLE
Interfaces don't support FieldResult type

### ISSUE THREAD

**Issue by phated** [sunli829/async-graphql#22]
It seems that Interfaces don't support the FieldResult type. This might be a scoping issue in the macro expansion?

Here is an example:

```rust
use async_graphql::FieldResult;

struct MyObj;

#[async_graphql::Object]
impl MyObj {
    #[field]
    async fn value_a(&self) -> FieldResult<i32> {
        Ok(1)
    }
}

#[async_graphql::Interface(field(name = "value_a", type = "FieldResult<i32>"))]
struct InterfaceA(MyObj);
```

**Comment by sunli829** [comment]
I’ll add it now.😊

**Comment by sunli829** [comment]
This feature is actually supported, but there is a bug that calls a deprecated function.
Upgrade to `v1.9.9`, the problem has been solved.😁

Here is the test code:
https://github.com/sunli829/async-graphql/blob/64d897a38433009ff6ff17dc13c3da249787ecb0/tests/interface.rs#L166

**Comment by phated** [comment]
This is working now. I am using it at https://github.com/phated/twentyfive-stars/blob/516bb22/server/src/data/card.rs#L28
