### ISSUE TITLE
Does async-graphql federation support subscriptions ?

### ISSUE THREAD

**Issue by Relaxe111** [sunli829/async-graphql#24]
Hello, i'm sorry if question is stupid. Does async-graphql federation support subscriptions form remote graphql schemes?

**Comment by sunli829** [comment]
No, that's a good question.😁
It's not that I don't want to support it, but federation doesn't. If it does, I can add it soon.
------------------------
https://www.apollographql.com/docs/apollo-server/federation/introduction/

**Comment by Relaxe111** [comment]
Thank you for quick answer. I hope they will ad it at some time :)
