### ISSUE TITLE
Accessing context within subscriptions

### ISSUE THREAD

**Issue by Ejhfast** [sunli829/async-graphql#25]
Thanks again for the great library and the fast response to my question yesterday! I now have a similar question around subscriptions. How do we pass data into the GraphQL resolver for a subscription? Here is pseudocode for what I would like to do:

```rust
pub async fn index_ws(
    schema: web::Data<ConvosSchema>,
    req: HttpRequest,
    payload: web::Payload,
    session: Session,
    db: web::Data<database::Database>
) -> Result<HttpResponse> {
    let user: Option<User> = user_from_session(db.users.clone(), db.sessions.clone(), session).await;
    // something like ".data(...)" to extend context does not seem to exist
    ws::start_with_protocols(WSSubscription::new(&schema).data(user), &["graphql-ws"], &req, payload)
}
```

And then:

```rust
#[async_graphql::Subscription]
impl SubscriptionRoot {
    #[field]
    async fn messages(&self, ctx: &Context<'_>, mutation_type: Option<MutationType>) -> impl Stream<Item = MessageChanged> {
        let current_user = ctx.data::<Option<User>>();
        // logic here, for example use current_user.id to filter a stream ...
    }
}
```

Is this possible? I reviewed the [subscription example](https://github.com/sunli829/async-graphql-examples/blob/master/models/books/src/lib.rs#L106) and didn't see anything. Looking over the implementation of the library, I also didn't see any way to add additional data to a subscription context, or access the context.

**Comment by sunli829** [comment]
I'm adding this feature.😃

**Comment by sunli829** [comment]
Adding this feature took a little longer than I expected. 😁

`async-graphql` upgrade to  `1.9.16`.
`async-graphql-actix-web` upgrade to `1.1.5` if you use `actix-web`.
`async-graphql-warp` upgrade to `1.1.5` if you use `warp`.

Example: https://github.com/sunli829/async-graphql-examples/blob/2337bcbbcb5bedb3cc2f3ebdb8f71cb6ba88f768/actix-web/token-from-header/src/main.rs#L57

You can test it in GraphQL playground.

**The token for the GraphQL subscription is sent by payload of the websocket protocol**

Set the following values into GraphQL playground HTTP Headers.
```json
{
  "token": "123456"
}
```

This is the actual subscription request sent through the websocket.
```
{"type":"connection_init","payload":{"token":"123456"}}
```

**Comment by nicolaiunrein** [comment]
Just in case anyone scratches their head like I did while trying to figure out how to embed the ctx into the stream.
Here is how I solved it using zip and repeat:
```rust
#[field]
async fn my_handler(&self, ctx: &Context<'_>) -> impl Stream<Item = MyEvent> {
    let repo = ctx.data::<BoxedRepository>();
    self.channel
        .subscribe()
        .zip(futures::stream::repeat(repo.clone()))
        .filter_map(|(_evt, _repo)| async move {
            //do something with repo like fetching data per event...
            None
        })
}


```

**Comment by sunli829** [comment]
Maybe you can try ‘Async-stream’.

**Comment by nicolaiunrein** [comment]
It does not seem to fix the problem that I cannot prove that the stream does not outlive the Context because the returned stream has a `'static` lifetime and `&Context` does not.

**Comment by Ejhfast** [comment]
Awesome work with the fast update! Just to give my current status, I also ran into an issue using my async DB representation within the stream:

```rust
#[async_graphql::Subscription]
impl SubscriptionRoot {
    #[field]
    async fn messages(&self, ctx: &Context<'_>, mutation_type: Option<MutationType>) -> impl Stream<Item = MessageChanged> {
        let convo_db = ctx.data::<Database>().conversations.clone();
        SimpleBroker::<MessageChanged>::subscribe().filter(move |event| {
            let convos = convo_db.get_all().await;
            // logic here...
            async move { res }
        })
    }
}
```

And `await` is not allowed, as it is not an async block.

Will see if this can be solved with `async-stream`. I imagine that many people would be interacting with context that presents async APIs, so maybe SimpleBroker should produce an async-compatible stream by default?

**Comment by nicolaiunrein** [comment]
I think this boils down to the same issue I was having. 
What do you mean by async-compatible?
I think it would be nice to be able to get a clone of the context with every event. Something like this:

```rust
SimpleBroker::<MyEvent>::subscribe_with_ctx().map(|(evt, ctx)| async move { evt })
```
Should be easy to implement and simplify client code. Are there better solutions? What do you think?

**Comment by Ejhfast** [comment]
@nicolaiunrein my Rust is not super strong, but I think there are two different problems here. One is the lifetime issue, giving whatever you want to pass into the stream a `'static` lifetime. I also ran into this issue but in my case was able to solve it by wrapping the data I wanted to share in `Arc`. 

```rust
let current_user = ctx.data::<Option<User>>();
let user_for_stream = Arc::new(current_user);
// then can use any data from the user inside the .filter(|x| ...) block because the lifetime is okay
```

But there is also the fact that the stream itself does not allow for calling async functions within the body of the filter (e.g., compiler error on any `.await`), which it looks like something like `async-stream` might solve. 

Does that make sense to you? In your case, would wrapping `repo` in an `Arc` also solve your problem? Or is this undesirable for other reasons?

**Comment by sunli829** [comment]
> It does not seem to fix the problem that I cannot prove that the stream does not outlive the Context because the returned stream has a `'static` lifetime and `&Context` does not.

Yes, this does not solve the lifetime problem.😄

**Comment by sunli829** [comment]
> I think this boils down to the same issue I was having.
> What do you mean by async-compatible?
> I think it would be nice to be able to get a clone of the context with every event. Something like this:
> 
> ```rust
> SimpleBroker::<MyEvent>::subscribe_with_ctx().map(|(evt, ctx)| async move { evt })
> ```
> 
> Should be easy to implement and simplify client code. Are there better solutions? What do you think?

@nicolaiunrein This is hard to implement, because the context borrows some data that can't be cloned, I think solve this problem by appending Arc<T> to the context data.

**Comment by sunli829** [comment]
@Ejhfast 

'StreamExt::map' can only accept one synchronous closure, you should use `StreamExt::then` replace `StreamExt::map`.

```rust
fn map<T, F>(self, f: F) -> Map<Self, F>
where
    F: FnMut(Self::Item) -> T

fn then<Fut, F>(self, f: F) -> Then<Self, Fut, F>
where
    F: FnMut(Self::Item) -> Fut,
    Fut: Future
```

`StreamExt::filter` does not have this problem

```rust
fn filter<Fut, F>(self, f: F) -> Filter<Self, Fut, F>
where
    F: FnMut(&Self::Item) -> Fut,
    Fut: Future<Output = bool>,
```

----------------------

**Your code above should be changed like this**

```rust
#[async_graphql::Subscription]
impl SubscriptionRoot {
    #[field]
    async fn messages(&self, ctx: &Context<'_>, mutation_type: Option<MutationType>) -> impl Stream<Item = MessageChanged> {
        let convo_db = ctx.data::<Database>().conversations.clone();
        SimpleBroker::<MessageChanged>::subscribe().filter(move |event| {
            async move {
               let convos = convo_db.get_all().await;
               // logic here...
               res
            }
        })
    }
}

**Comment by nicolaiunrein** [comment]
To recap: I guess the trick is to move your data into the closure, clone it and move the clone into the `async` block. This seems to work with or without `Arc` but for performance reasons this should of course be an `Arc` on most types to avoid expensive clones.  My problem was that I always moved the data straight to the `async` block and tried to clone there.

**Comment by sunli829** [comment]
This should be the best solution.

**Comment by Dindaleon** [comment]
Is this still working? Because I tried it and getting the following error:

`hidden type for `impl Stream<Item = BookChanged>` captures lifetime that does not appear in bounds`
