### ISSUE TITLE
Defining fields in traits

### ISSUE THREAD

**Issue by nicolaiunrein** [sunli829/async-graphql#28]
I just thought it would be really neat to move some common fields from my concrete impl blocks to a shared trait.  I can think of a lot of situations where this might be handy:

- DRYing code
- Composing types
- Ensuring consistency 
- Libraries exposing GQL endpoints for user defined types etc.

So Is this possible?

**Comment by sunli829** [comment]
Can you give me an example?😄

**Comment by nicolaiunrein** [comment]
Imagine something like this: 
```rust
#[async_trait]
#[TraitObject] // or something similar
pub trait Info {
   async fn get_info(&self) -> InfoObject; 

   #[field]
   async fn uptime(&self) -> String {
    self.get_info().uptime()
   }

   #[field]
   async fn name(&self) -> String {
    self.get_info().name()
   }
}

pub struct MyInfo;

impl Info for MyInfo {
    async fn get_info(&self) -> InfoObject {
        InfoObject::new();
    }
}

#[Object]
impl MyInfo {
    #[field]
    async fn additional_field(&self) -> &str {
       "This will also be available" 
    }
}

pub struct QueryRoot;

impl QueryRoot {
    async fn info(&self) -> MyInfo {
        MyInfo::{}
    } 
}


```

Which allows you run queries like this:
```graphql
query {
    info {
        uptime
        name
        additionalField
    }
}
```

This example is quite silly but I think it reflects the idea of what I am trying to accomplish.

**Comment by nicolaiunrein** [comment]
Maybe you could even do something like:
```rust
impl QueryRoot {
    async fn info(&self) -> Box<dyn Info> {
        MyInfo::{}
    } 
}
```

**Comment by sunli829** [comment]
Let me think about how do I do this.😆

**Comment by nicolaiunrein** [comment]
I think returning trait objects will not work because of introspection queries though.

**Comment by nicolaiunrein** [comment]
To help you better understand my concrete needs: I have a bunch of services which each needs to provide a query of the same type but fetching that data depends on the implementation of the individual service. So if the above was possible, I could extract the trait to a shared crate and implement it for every service giving me consistent results and clean code. I could implement something like this with existing tools but not as clean and idiomatic. I would need to have a shared struct as an Object and have it store a Box of my shared trait.

**Comment by sunli829** [comment]
I fully understand your purpose.😁

**Comment by sunli829** [comment]
Add the property `flatten` to #[field], flatten the contents of this field into the container it is defined in. how about this?

```rust
trait InfoObject {
    async fn uptime(&self);
    async fn name(&self) -> String;
}

struct GQLInfoObject(Box<dyn InfoObject>);

#[Object]
impl GQLInfoObject {
    #[field]
    async fn uptime(&self) -> String {
        self.0.uptime()
    }

    #[field]
    async fn name(&self) -> String {
        self.0.name()
    }
}

#[Object]
impl MyInfo {
    #[field(flatten)]
    async fn info(&self) -> GQLInfoObject {
        GQLInfoObject(self.get_info_object())
    }

    #[field]
    async fn additional_field(&self) -> &str {
        "This will also be available"
    }
}

pub struct QueryRoot;

impl QueryRoot {
    async fn info(&self) -> MyInfo {
        unimplemented!()
    } 
}

```

```GraphQL
query {
    info {
        uptime
        name
        additionalField
    }
}
```

**Comment by nicolaiunrein** [comment]
I think this could work. What happens on nested fields? I guess flatten reduces by one level?

**Comment by sunli829** [comment]
Right, the behavior is the same as in the serde.

**Comment by nicolaiunrein** [comment]
Would something like this also work?
```rust
trait InfoObject {
    async fn uptime(&self);
    async fn name(&self) -> String;
}

#[Interface(
    field(name="name", type="String"),
    field(name="uptime", type="String"),
]
struct GQLInfoObject(Box<dyn InfoObject>);


```

**Comment by sunli829** [comment]
I can't do that right now. I can't get the `GraphQLType` for `InfoObject`.

**Comment by sunli829** [comment]
Maybe rust's constant generics will be stable enough to be implemented.

**Comment by nicolaiunrein** [comment]
I think being able to do something like in your example would be awesome. What about SimpleObject? Would it work there as well? 
```rust
#[SimpleObject]
struct MyObj {
    #[field(flatten)]
    pub info: Box<dyn InfoObject>
}
```

**Comment by sunli829** [comment]
Yes, it can also do. 😄

**Comment by nicolaiunrein** [comment]
Got it!

**Comment by sunli829** [comment]
I am adding it now.😁

**Comment by sunli829** [comment]
Flatten doesn't work. There are some other problems. I'll think of another way.☹️

**Comment by sunli829** [comment]
Why don't you try macros? I didn't find a good solution.😕

**Comment by nicolaiunrein** [comment]
Don’t worry I’ll find a solution to my problem. I just thought it would be something nice to have.

**Comment by sunli829** [comment]
Well, procedural macros have some limitations, and many ideas are impossible to implement.😠

**Comment by nicolaiunrein** [comment]
What about having a compose attribute on Object where you pass in the name and getter of the fields you want to resolve where the getter has is defined on an implemented trait.

**Comment by sunli829** [comment]
Something like `Interface`, right?

**Comment by nicolaiunrein** [comment]
```rust
trait MyTrait {
    fn test(&self) -> &str {
        "it works"
    }
}

#[Object(
    compose(
        field(name="test", getter="test"),
    ),
)]
struct MyStruct;
```

Yes a little bit like Interface.

**Comment by sunli829** [comment]
Like this:

```rust
trait Info {
   async fn name(&self) -> String;
}

#[Object(
    field(name = "name", type = "String")
)]
impl Query {
}
```

```graphql
{
    name
}
```

**Comment by sunli829** [comment]
That's a good idea, and it can be implemented! I'll do it right now.😁

**Comment by nicolaiunrein** [comment]
What happens when two implemented traits have the same method. I would need to specify a fully qualified path to the method which is not a nice field name. 😆 Maybe we should have a "method" attribute and an optional "rename" attribute

**Comment by nicolaiunrein** [comment]
```rust

trait InfoA {
   async fn name(&self) -> String;
   async fn uptime(&self) -> i32;
}

trait InfoB {
   async fn name(&self) -> String;
}

#[Object(
    field(method = "InfoA::name", type = "String", rename = "name_a"),
    field(method = "InfoB::name", type = "String", rename = "name_b"),
    field(method = "uptime", type = "i32")

)]
impl Query {
}

```

```graphql
{
    nameA
    nameB
    uptime
}
```

**Comment by nicolaiunrein** [comment]
And maybe as a next step we can have an optional "getter" attribute. This would enable us to use traits already defined or from other crates:
```rust
trait Info {
   async fn info(&self) -> SomeType;  // SomeType implements ToString
}

#[Object(
    field(name = "info",  type = "String", getter = "std::string::ToString")
)]
impl Query {
}
```

```GraphQL
{
    info
}
```

**Comment by sunli829** [comment]
I suddenly feel like this thing doesn't make any sense.😂

```rust
trait Info {
   async fn name(&self) -> String;
}

impl Query {
    #[field]
    fn name(&self) -> String {
      <Self as Info>::name()
    }
}
```

It's just one line of code, and it's only written once.

**Comment by nicolaiunrein** [comment]
Well maybe your are right and we are chasing our tail 😆.  What we really want is this:
```rust

#[Object]
trait Info {
   #[field]
   async fn name(&self) -> &str {
       "it works"
    }
}

struct MyInfo;
impl Info for MyInfo{}

impl Query {
    fn info(&self) -> MyInfo {
      MyInfo
    }
}
```

```GraphQL
{
    info {
      name
    }
}
```

**Comment by sunli829** [comment]
There's no way to do that.😂

**Comment by nicolaiunrein** [comment]
I know. 😂. So to summarise: All solutions are either impossible to implement or trivial. The best idea is a "flatten" attribute which is also not possible as of now but maybe in the future. So I close this issue and open a new one as a feature request for "flatten".
