### ISSUE TITLE
Accept a SimpleObject as input type.

### ISSUE THREAD

**Issue by ruseinov** [sunli829/async-graphql#32]
Currently if I want to define a struct with a bunch of fields as an InputType I would also have to define the `impl` for it and all the fields there, which makes the amount of boilerplate unbearable. 

I'd like to be able to simply define a struct and use it's fields as input fields.

**Comment by ruseinov** [comment]
My bad, it looks like the object is not accepted either. I'm not sure how this is supposed to worth then as the docs are pretty scarce on this subject, I'll keep investigating.

**Comment by ruseinov** [comment]
```#[InputObject]``` there we go. I was misled by rust compiler errors at first.

**Comment by sunli829** [comment]
The documentation is not detailed enough.😂

**Comment by ruseinov** [comment]
@sunli829 yeah, the rest works though. Once I'm done with my graphql implementation and I'm doing a full on Mutation/Subscription/Query impl backend by MongoDB - I'll make sure to contribute some boilerplate. 

It would also be nice to somehow be able to expose all fields by default without supplying `#[field]` annotation, but I haven't tested without. I'll be happy to come back with a bunch of proposals once I'm further down this road.

**Comment by sunli829** [comment]
This is a good suggestion, I created a new issue #33  and started adding this feature now.

**Comment by ruseinov** [comment]
Oh wow, that was quick, thanks!
