### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by sunli829** [sunli829/async-graphql#5]

**Comment by geofmureithi** [comment]
I would suggest a subscription with Stream?

**Comment by sunli829** [comment]
Yes, I'm working on it. I think I can get it done the day after tomorrow.

**Comment by geofmureithi** [comment]
Would you need any help?

**Comment by sunli829** [comment]
There are two main problems that have not been solved:

1. The guide book, similar to https://graphql-rust.github.io/juniper/current/
2. More test code

I'd appreciate it if you could help me with some of this! 😁

**Comment by sunli829** [comment]
Stream-based subscriptions, which may not be necessary, I dropped the change. GraphQL Subscription is usually based on a websocket connection. You should use 'async-graphql-acx-web' crate, which already provides everything you need.

**Comment by geofmureithi** [comment]
Will check it out. 
I can help with test code. Where should I start?

**Comment by sunli829** [comment]
src/validation/rules need to test.
You first need to create a schema for the tests, and then write the test code for each rule.
Take a look at `juniper`, its test code is comprehensive.

**Comment by geofmureithi** [comment]
Hey been unable to help due to the current status of things. Lets see how things go.

**Comment by sunli829** [comment]
I'm write an example and you can see if you can do it together？

**Comment by geofmureithi** [comment]
Sure, that would help.
