### ISSUE TITLE
Integration with dataloader to solve N+1 query problem

### ISSUE THREAD

**Issue by cksac** [sunli829/async-graphql#8]
I am trying to make `async-graphql` work with `dataloader`, [examples](https://github.com/cksac/dataloader-rs/tree/master/examples).
`cargo run --example juniper`
`cargo run --example async_graphql`

the async-await branch of `juniper` is able to do batch load, but `async-grapqhl` still not able to do so.

**Comment by sunli829** [comment]
This is because `async-graphql` does not yet support concurrent resolver, I'm adding this feature.

**Comment by sunli829** [comment]
I fixed this problem, please upgrade to `1.5.1`.
