### ISSUE TITLE
Support Error Extensions

### ISSUE THREAD

**Issue by nicolaiunrein** [sunli829/async-graphql#9]
Hey,
first of all, I really enjoy using your library so far. I think it is already very comprehensive. One thing I am missing though is returning extensions for errors as described [here](https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md) in the spec. Something like: 
```{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

In terms of api, I think it would be nice to have a trait with a single method `with_extensions` which you could implement on your errors. Something like: 
```
// somewhere in async-graphql
pub trait ErrorExtensions {
    fn with_extensions(&self) -> Option<serde_json::Value> {
        None
    }
}

impl<T: Into<Error>> ErrorExtensions for T {}
```
```
// somewhere in users code...
impl ErrorExtensions for MyError {
  fn with_extensions(&self) -> Option<serde_json::Value> {

    let extensions = serde_json::json!({
       "code": self.code.to_string(),
       "timestamp": get_current_timestamp()
    });

    Some(extensions)
  }
}
```

I am happy to contribute, so if you want any help just let me know.

**Comment by sunli829** [comment]
Thank you for your advice, that's a great idea, and I really need your help. These days I want to optimize the code in the subscription to make it easier to use, so our work doesn't conflict.If you have time, you can help implement `ErrorExtensions'.😁
Thanks again!

**Comment by nicolaiunrein** [comment]
I thought a little about it and started implementing a first draft. Will be ready for review tomorrow or on monday I think.

**Comment by sunli829** [comment]
Is it a wrapper similar to `PositionError`?

**Comment by nicolaiunrein** [comment]
> Is a wrapper similar to `PositionError`?

Yes exactly. See PR for details.

**Comment by sunli829** [comment]
I reimplemented the error type in branch `error-type`, the error extension is still not very good, give some advice?

**Comment by nicolaiunrein** [comment]
I looked at the `error-type` and made some adjustments. Please have a look and also at the example uses cases. It turns out to be quite tricky to implement some sort of default implementation but still let the user implement custom behaviour. Feel free to undo the commit if you don't like it.

**Comment by nicolaiunrein** [comment]
I also replaced the trait bound std::err::Error with std::fmt::Display because I think Error is an unnecessary restriction.

**Comment by sunli829** [comment]
Thank you, It's merged to master.😁
